config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#frontdoor'
  get '/dashboard', to: 'dashboard#home'
  get '/admin_panel', to: 'dashboard#admin_panel'

  resources :seasons
  resources :events do
    get   'forecasts/observed/edit', to: 'forecasts#edit_observed'
    patch  'forecasts/observed', to: 'forecasts#update_observed'
    resources :forecasts
  end

  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  # validations
  validates :start_date, presence: true
  validates :duration, presence: true

  # associations
  belongs_to :season
  has_many :forecasts
  has_one :event_record
  has_one :observed_forecast, class_name: "Forecast", through: :event_record

  def end_date
    start_date + duration.days - 1.second
  end

  def status
    status = "Active"

    if is_upcoming?
      status = "Upcoming"
    elsif is_completed?
      status = "Completed"
    end
  end

  def is_active?
    today = DateTime.now
    today > start_date && today < end_date
  end

  def is_completed?
    DateTime.now > end_date
  end

  def is_upcoming?
    DateTime.now < start_date
  end
end

app/models/event_record.rb
class EventRecord < ApplicationRecord
  # validations

  # associations
  belongs_to :event
  belongs_to :observed_forecast, class_name: "Forecast", optional: true
end

app/models/forecast.rb
class Forecast < ApplicationRecord

  # validations
  validates :precipitation, numericality: { greater_than_or_equal_to: 0.0, allow_nil: true }
  validates :wind, numericality: { greater_than_or_equal_to: 0, allow_nil: true }

  # associations
  belongs_to :season
  belongs_to :event

  # If the forecast is the observed forecast, then it does not need to be associated with a user
  belongs_to :user, optional: true
end

app/models/organization.rb
class Organization < ApplicationRecord

  # validations
  validates :name, presence: true

  # associations
  belongs_to :owner, class_name: "User"
  has_and_belongs_to_many :users
end

app/models/season.rb
class Season < ApplicationRecord

  # validations
  validates :name, presence: true

  # associations
  has_many :events
  has_many :forecasts
  belongs_to :owner, class_name: "User"

  accepts_nested_attributes_for :events, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # associations
  has_many :forecasts
  has_many :seasons
  has_one :owned_organization, class_name: "Organization", foreign_key: "owner_id"
  has_and_belongs_to_many :organizations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


    def authenticate_user!(options={})
      if user_signed_in?
        super
      else
        redirect_to new_user_session_path
      end
    end

    def after_sign_in_path_for(resource)
      dashboard_path
    end

    def authenticate_admin_user!(options={})
      if !(authenticate_user!(options) && current_user.admin?)
        redirect_to dashboard_path, alert: "1003 - Must be admin to access this page."
      end
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :authenticate_user!, only: [:home]
  before_action :authenticate_admin_user!, only: [:admin_panel]

  def frontdoor

  end

  def home
    @seasons = [Season.first]
  end

  def admin_panel
  end

  private
    def get_active_seasons
      # TODO Refine this algorithm as seasons evolve during development
      Season.joins(:events).group('season.id').to_a;
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!

  def show
    @event        = Event.find(params[:id])
    @forecast     = Forecast.find_by(event: @event, user: current_user)

    # TODO replace placeholder for the actual observations.
    @observation  = @event.observed_forecast
  end
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController

  before_action :authenticate_user!

  def new
    @event = Event.find(params[:event_id])
    validate_event_exists(@event)

    @forecast = Forecast.find_by(event: @event, user: current_user)

    # A user should only have one forecast per event. If a forecast already
    # exists for a user, lets have them edit that forecast instead
    if @forecast
      redirect_to edit_event_forecast_path(@event, @forecast)
    end

    @forecast = Forecast.new
  end

  def create
    # TODO make season and event required, write specs to test this
    @event = Event.find(params[:event_id])
    validate_event_exists(@event)

    @forecast         = Forecast.new(forecast_params)
    @forecast.event   = @event
    @forecast.season  = @event.season
    @forecast.user    = current_user

    if @forecast.save
      redirect_to @event
    else
      render "new"
    end
  end

  def edit
    @event = Event.find(params[:event_id])
    validate_event_exists(@event)

    @forecast = Forecast.find(params[:id])
    validate_forecast_owner(@forecast)
  end

  def update
    @event = Event.find(params[:event_id])
    @forecast = Forecast.find(params[:id])

    if @forecast.update(forecast_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def edit_observed
    @event = Event.find(params[:event_id])
    validate_event_exists(@event)
    @forecast = @event.observed_forecast || Forecast.new
  end

  def update_observed
    @event = Event.find(params[:event_id])
    validate_event_exists(@event)
    @forecast = @event.observed_forecast || Forecast.new
    @forecast.attributes = forecast_params

    if @forecast.save
      redirect_to @event
    else
      render 'edit_observed'
    end
  end

  private
    def forecast_params
      params.require(:forecast).permit(:high_temp, :low_temp, :precipitation, :wind)
    end

    def validate_event_exists(event)
      if !event
        redirect_to dashboard_path, alert: "1001 - Error building forecast."
      end
    end

    def validate_forecast_owner(forecast)
      if(!forecast || !forecast.user  || forecast.user != current_user)
        redirect_to dashboard_path, alert: "1002 - Cannot edit other users forecast."
      end
    end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

  before_action :authenticate_admin_user!
  before_action :find_season, only: [:show, :edit, :update, :destroy]

  def index
    @seasons = Season.all
  end

  def show
  end

  def new
    @season = Season.new
    2.times{ @season.events.build }
  end

  def create
    @season = Season.new(season_params)
    @season.owner = current_user

    if @season.save
      redirect_to @season
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @season.update(season_params)
      redirect_to @season
    else
      render 'edit'
    end
  end

  def destroy
    if @season.destroy
      redirect_to seasons_path
    else
      redirect_to @season
    end
  end

  private
    def season_params
      params.require(:season).permit(:name, events_attributes: [:id, :start_date, :duration, :location, :station, :_destroy])
    end

    def find_season
      @season = Season.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/admin_panel.html.erb
<h1>Admin Panel</h1>

<%= link_to "Seasons", seasons_path %><br>
<%= link_to "Add New Season", new_season_path %><br>

app/views/dashboard/frontdoor.html.erb
<h1>Frontdoor</h1>

<%= link_to "Login", new_user_session_path %><br>
<%= link_to "Sign Up", new_user_registration_path %><br>

app/views/dashboard/home.html.erb
<h1>Dashboard</h1>

<% @seasons.each do |season| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-heading-text"><%= link_to season.name, season_path(season), class: "undecorrated-link" %></h3>
    </div>

    <div class="panel-body">
      <div class="row">
        <% season.events.each do |event| %>
          <div class="col-md-3">
            <%= link_to(event, class: "undecorrated-link") do %>
              <div class="thumbnail">
                <h4 class="event-thumbnail-heading"><%= event.station %></h4>
                <p>
                  <i><%= event.location %></i>
                </p>

                <% if event.is_completed? %>
                  <!-- TODO scope to user's forecast once user is introduced -->
                  <div class="row">
                    <div class="col-md-4">
                      <p>
                        Score:
                      </p>
                    </div>
                    <div class="col-md-8">
                      <p>
                        <%= event.forecasts.first.score %>
                      </p>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-4">
                      <p>
                        Position:
                      </p>
                    </div>
                    <div class="col-md-8">
                      <p>
                        4 / 28
                      </p>
                    </div>
                  </div>
                <% else %>
                  <div class="row">
                    <div class="col-md-3">
                      <p>
                        Due:
                      </p>
                    </div>
                    <div class="col-md-9">
                      <p>
                        <%= event.start_date.strftime("%H:%M %Z - %m.%d.%Y") %><br>
                        <span style="color: red;">( in 4 hours )</span>
                      </p>
                    </div>
                  </div>
                <% end %>

              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h3><%= @event.season.name %> - <%= @event.station %></h3>
  </div>
</div>

<!-- TODO scope this block to the season owner / creator -->
<% if current_user.admin? %>
  <div class="row panel" style="margin: 30px 0px; padding: 10px 0px; border: 1px solid #a94442;">
    <div class="col-md-12">
      <div class="col-md-2">
        <h5 class="text-danger">Admin Only</h5>
      </div>
      <div class="col-md-10">
        <% if @event.is_completed? %>
          <%= button_to "Enter Actual Forecast Observations", event_forecasts_observed_edit_path(@event), method: :get, class: "btn btn-success" %>
        <% else %>
          <%= button_to "Enter Actual Forecast Observations", "#", class: "btn btn-success", disabled: true %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-4">
    <div class="row">
      <div class="col-md-4">
        <p><strong>My Status:</strong></p>
      </div>
      <div class="col-md-8">
        <p><%= @forecast ? "Submitted" : "Not Submitted" %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <% if !@observation %>
          <% if @forecast %>
            <%= button_to "Update My Forecast", new_event_forecast_path(@event), method: "get", class: "btn btn-warning" %>
          <% else %>
            <%= button_to "Submit My Forecast", new_event_forecast_path(@event), method: "get", class: "btn btn-success" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-4">

    <div class="row">
      <div class="col-md-4">
        <p><strong>Location:</strong></p>
      </div>
      <div class="col-md-8">
        <p><%= @event.location %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <p><strong>Station:</strong></p>
      </div>
      <div class="col-md-8">
        <p><%= @event.station %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <p><strong>Start Date:</strong></p>
      </div>
      <div class="col-md-8">
        <p><%= @event.start_date %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <p><strong>End Date:</strong></p>
      </div>
      <div class="col-md-8">
        <p><%= @event.end_date %></p>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="well well-sm">
      <div class="row">
        <div class="col-md-12 text-center">
          <p><strong>Resources</strong></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= link_to "Current Station Observation", "http://w1.weather.gov/xml/current_obs/#{@event.station}.xml", target: "_blank" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= link_to "3-Day Historical Station Observations", "http://w1.weather.gov/data/obhistory/#{@event.station}.html", target: "_blank" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= link_to "3-Day Station Observations Forecast", "http://www.nws.noaa.gov/cgi-bin/mos/getall.pl?sta=#{@event.station}", target: "_blank" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row" style="margin-top: 30px;">
  <div class="col-md-12">
    <table class="table table-hover">
      <tr>
        <th class="col-md-4">Measurement</th>
        <th class="col-md-2">My Forecast</th>
        <th class="col-md-2">Actual Observation</th>
        <th class="col-md-2">Difference</th>
        <th class="col-md-2">Score</th>
      </tr>
      <tr>
        <td>High Temperature</td>
        <td><%= @forecast ? @forecast.high_temp : "-" %></td>
        <td><%= @observation ? @observation.high_temp : "-" %></td>
        <td><%= @observation ? @forecast.high_temp - @observation.high_temp : "-" %></td>
        <td><%= @observation ? "0.5" : "-" %></td>
      </tr>
      <tr>
        <td>Low Temperature</td>
        <td><%= @forecast ? @forecast.low_temp : "-" %></td>
        <td><%= @observation ? @observation.low_temp : "-" %></td>
        <td><%= @observation ? @forecast.low_temp - @observation.low_temp : "-" %></td>
        <td><%= @observation ? "0.5" : "-" %></td>
      </tr>
      <tr>
        <td>Precipitation</td>
        <td><%= @forecast ? @forecast.precipitation : "-" %></td>
        <td><%= @observation ? @observation.precipitation : "-" %></td>
        <td><%= @observation ? @forecast.precipitation - @observation.precipitation : "-" %></td>
        <td><%= @observation ? "0.5" : "-" %></td>
      </tr>
      <tr>
        <td>Wind</td>
        <td><%= @forecast ? @forecast.wind : "-" %></td>
        <td><%= @observation ? @observation.wind : "-" %></td>
        <td><%= @observation ? @forecast.wind - @observation.wind : "-" %></td>
        <td><%= @observation ? "0.5" : "-" %></td>
      </tr>
      <tr>
        <td colspan="4">
          <strong><i>Total Points:</i></strong>
        </td>
        <td>
          <strong><i><%= @observation ? "27.9" : "-" %></i></strong>
        </td>
      </tr>
    </table>
  </div>
</div>

app/views/forecasts/_forecast_fields.html.erb
<div class="form-group">
  <label class="col-md-2 control-label">
    Season
  </label>
  <div class="col-md-10">
    <p style="margin-bottom:0px; margin-top:6px;"><%= @event.season.name %></p>
  </div>
</div>

<div class="form-group">
  <label class="col-md-2 control-label">
    Event
  </label>
  <div class="col-md-10">
    <p style="margin-bottom:0px; margin-top:6px;"><%= @event.station %></p>
  </div>
</div>

<div class="form-group">
  <%= f.label :high_temp, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.number_field :high_temp, step: 1, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :low_temp, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.number_field :low_temp, step: 1, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :precipitation, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.number_field :precipitation, step: 0.01, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :wind, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.number_field :wind, step: 1, min: 0, class: "form-control" %>
  </div>
</div>

app/views/forecasts/edit.html.erb
<div class="text-center">
  <h1>Edit Forecast</h1>
</div>

<%= form_for [@event, @forecast], html: { class: "form-horizontal" } do |f| %>
  <%= render 'forecast_fields', f: f %>

  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/forecasts/edit_observed.html.erb
<div class="text-center">
  <h1>Edit Observed Forecast</h1>
</div>

<%= form_for [@event, @forecast], url: event_forecasts_observed_path(@event), method: "patch", html: { class: "form-horizontal" } do |f| %>
  <%= render 'forecast_fields', f: f %>

  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/forecasts/new.html.erb
<div class="text-center">
  <h1>New Forecast</h1>
</div>

<%= render 'forecast_form' %>

app/views/layouts/_alert_banner.html.erb
<% if alert %>
  <div class="alert alert-danger alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p><%= alert %></p>
  </div>
<% elsif notice %>
  <div class="alert alert-warning alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p><%= notice %></p>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" style="margin-bottom: 0px;">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=
        if user_signed_in?
          link_to "Journeyman Forecaster", dashboard_path, class: "navbar-brand"
        else
          link_to "Journeyman Forecaster", root_path, class: "navbar-brand"
        end
      %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <% if(current_user && current_user.admin?) %>
            <li class="dropdown">
              <%= link_to "Admin Panel", admin_panel_path, class: "text-danger" %>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Settings", edit_user_registration_path %>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
              </li>

            </ul>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journeyman</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>

    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alert_banner' %>

    <div class="container" style="margin-top: 30px;">
      <%= yield %>
    </div>

  </body>
</html>

app/views/seasons/_event_fields.erb
<div class="form-group row fields">
  <div class="col-md-3">
    <%= f.text_field :start_date, class: "form-control datepicker", data: { provide:'datepicker' },
      placeholder: "Start Date"%>
  </div>

  <div class="col-md-2">
    <%= f.number_field :duration, class: "form-control", placeholder: "Duration" %>
  </div>

  <div class="col-md-3">
    <%= f.text_field :location, class: "form-control", placeholder: "Location" %>
  </div>

  <div class="col-md-2">
    <%= f.text_field :station, class: "form-control", placeholder: "Station" %>
  </div>

  <div class="col-md-1">
    <%= link_to "remove", "javascript:void(0);", class: "remove_link",
          onclick: "remove_fields(this)"%>
  </div>

  <%= f.hidden_field :_destroy, class: "hidden-destroy" %>
</div>

app/views/seasons/_event_fields.html.erb
<div class="form-group row fields">
  <div class="col-md-3">
    <%= f.text_field :start_date, class: "form-control datepicker", data: { provide:'datepicker' },
      placeholder: "Start Date"%>
  </div>

  <div class="col-md-2">
    <%= f.number_field :duration, class: "form-control", placeholder: "Duration" %>
  </div>

  <div class="col-md-3">
    <%= f.text_field :location, class: "form-control", placeholder: "Location" %>
  </div>

  <div class="col-md-2">
    <%= f.text_field :station, class: "form-control", placeholder: "Station" %>
  </div>

  <div class="col-md-1">
    <%= link_to "remove", "javascript:void(0);", class: "remove_link",
          onclick: "remove_fields(this)"%>
  </div>

  <%= f.hidden_field :_destroy, class: "hidden-destroy" %>
</div>

app/views/seasons/_season_fields.erb
<div class="form-group">
  <%= f.label :name, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :name, class: "form-control", placeholder: "Season Name" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :events, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <div class="panel panel-default">
      <div class="panel-body fields-container">

        <%= f.fields_for :events do |ff| %>
          <%= render 'event_fields', f: ff %>
        <% end %>

        <button type="button" class="btn btn-default btn-sm" onclick="add_fields(this)">Add Season</button>

      </div>
    </div>
  </div>
</div>

app/views/seasons/_season_fields.html.erb
<div class="form-group">
  <label class="col-md-2 control-label">
    Owner
  </label>
  <div class="col-md-10">
    <p class="help-block"><%= current_user.email %></p>
  </div>
</div>

<div class="form-group">
  <%= f.label :name, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :name, class: "form-control", placeholder: "Season Name" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :events, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <div class="panel panel-default">
      <div class="panel-body fields-container">

        <%= f.fields_for :events do |ff| %>
          <%= render 'event_fields', f: ff %>
        <% end %>

        <button type="button" class="btn btn-default btn-sm" onclick="add_fields(this)">Add Season</button>

      </div>
    </div>
  </div>
</div>

app/views/seasons/edit.html.erb
<div class="text-center">
  <h1>Edit Season</h1>
</div>

<%= form_for @season, html: { class: "form-horizontal" } do |f| %>

  <%= render "season_fields", f: f %>

  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/seasons/index.html.erb
<% @seasons.each do |season| %>
  <p><%= season.name %></p>
<% end %>

app/views/seasons/new.html.erb
<div class="text-center">
  <h1>New Season</h1>
</div>

<%= form_for @season, html: { class: "form-horizontal" } do |f| %>

  <%= render "season_fields", f: f %>

  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <%= f.submit "Create", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/seasons/show.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h3><%= @season.name %></h3>
  </div>
</div>

<div class="row">
  <h4>Events:</h4>
  <table class="table">
    <tr>
      <th>Station</th>
      <th>Location</th>
      <th>Start</th>
      <th>End</th>
      <th>Status</th>
      <th></th>
    </tr>

    <% @season.events.each do |event| %>
      <tr>
        <td><%= event.station %></td>
        <td><%= event.location %></td>
        <td><%= event.start_date %></td>
        <td><%= event.end_date %></td>
        <td><%= event.status %></td>
        <td>
          <button class="btn btn-default btn-xs">View</button>
          <button class="btn btn-default btn-xs">Edit</button>
          <button class="btn btn-default btn-xs">Delete</button>
        </td>
      </tr>
    <% end %>

  </table>
</div>